name: hiersigcwganenv
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py38_0
  - openssl=1.1.1h
  - pip=20.2.3=py38_0
  - python=3.8.3
  - setuptools=49.6.0=py38_1
  - sqlite=3.33.0
  - wheel=0.35.1=py_0
  - zlib=1.2.11
  - pip:
    - cycler==0.10.0
    - joblib==0.17.0
    - kiwisolver==1.2.0
    - matplotlib==3.3.2
    - numpy==1.19.2
    - pandas==1.0.3
    - pillow==7.2.0
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.1
    - scikit-learn==0.23.1
    - scipy==1.4.1
    - signatory==1.2.1.1.4.0
    - six==1.15.0
    - threadpoolctl==2.1.0
    - torch==1.4.0  # torch==1.4.0 gpu cuda 10.1
    - torchvision==0.5.0  # torch==0.5.0 gpu cuda 10.1
    - tqdm==4.50.0


